<a href="https://colab.research.google.com/github/rtajeong/M1_2025/blob/main/gg04_pandas_rev6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas - basic
- 데이터프레임(Dataframe)과 시리즈(Series)

## indices and columns

In [ ]:
# 시리즈와 데이터프레임 두가지가 기본이다
# 자동으로 인덱스가 만들어진다

import numpy as np
import pandas as pd

In [ ]:
dic = {'city': ['서울', '부산', '대전', '대구', '광주'],
        'year': [2017, 2017, 2018, 2018, 2018],
        'temp': [18, 20, 19, 21, 20]}
data = pd.DataFrame(dic) ; data

  city  year  temp
0   서울  2017    18
1   부산  2017    20
2   대전  2018    19
3   대구  2018    21
4   광주  2018    20

In [ ]:
data['city'], type(data['city'])

(0    서울
 1    부산
 2    대전
 3    대구
 4    광주
 Name: city, dtype: object,
 pandas.core.series.Series)

In [ ]:
data[['year', 'city']]

   year city
0  2017   서울
1  2017   부산
2  2018   대전
3  2018   대구
4  2018   광주

In [ ]:
data.columns

Index(['city', 'year', 'temp'], dtype='object')

In [ ]:
data.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
data.index = ['a','b','c','d','e'] ; data

  city  year  temp
a   서울  2017    18
b   부산  2017    20
c   대전  2018    19
d   대구  2018    21
e   광주  2018    20

In [ ]:
data.columns = ['도시','연도','날씨']

In [ ]:
data

   도시    연도  날씨
a  서울  2017  18
b  부산  2017  20
c  대전  2018  19
d  대구  2018  21
e  광주  2018  20

In [ ]:
data.set_index(['도시'], inplace=True)

In [ ]:
data

      연도  날씨
도시
서울  2017  18
부산  2017  20
대전  2018  19
대구  2018  21
광주  2018  20

## Accessing columns, indexing and slicing, drop

In [ ]:
# accessing specific columns
data['연도']   # column 값으로접근

도시
서울    2017
부산    2017
대전    2018
대구    2018
광주    2018
Name: 연도, dtype: int64

In [ ]:
data.연도     # 속성 값으로 접근

도시
서울    2017
부산    2017
대전    2018
대구    2018
광주    2018
Name: 연도, dtype: int64

In [ ]:
data

      연도  날씨
도시
서울  2017  18
부산  2017  20
대전  2018  19
대구  2018  21
광주  2018  20

In [ ]:
data[['연도','날씨']]   # multiple columns

      연도  날씨
도시
서울  2017  18
부산  2017  20
대전  2018  19
대구  2018  21
광주  2018  20

In [ ]:
# accessing specific rows - two ways (index name, index number)
data.loc['서울']   # index name

연도    2017
날씨      18
Name: 서울, dtype: int64

In [ ]:
data.loc[['서울','부산']]

      연도  날씨
도시
서울  2017  18
부산  2017  20

In [ ]:
data.iloc[1:5]    # index number (like an array)

      연도  날씨
도시
부산  2017  20
대전  2018  19
대구  2018  21
광주  2018  20

In [ ]:
data.loc['부산':'광주']  # 위와 동일 (차이점은 마지막 부분이 포함된다는 것)

      연도  날씨
도시
부산  2017  20
대전  2018  19
대구  2018  21
광주  2018  20

In [ ]:
data.iloc[1:5]

      연도  날씨
도시
부산  2017  20
대전  2018  19
대구  2018  21
광주  2018  20

In [ ]:
data.iloc[:, 0:2]    # multiple columns (like an array)

      연도  날씨
도시
서울  2017  18
부산  2017  20
대전  2018  19
대구  2018  21
광주  2018  20

In [ ]:
# 새로운 열 추가 (feature)
cars = [50,40,20,30,10]
data['car'] = cars ; data

      연도  날씨  car
도시
서울  2017  18   50
부산  2017  20   40
대전  2018  19   20
대구  2018  21   30
광주  2018  20   10

In [ ]:
data['high'] = (data.car >= 30) ; data

      연도  날씨  car   high
도시
서울  2017  18   50   True
부산  2017  20   40   True
대전  2018  19   20  False
대구  2018  21   30   True
광주  2018  20   10  False

In [ ]:
data.drop('대전')   # remove row

      연도  날씨  car   high
도시
서울  2017  18   50   True
부산  2017  20   40   True
대구  2018  21   30   True
광주  2018  20   10  False

In [ ]:
data.drop('car', axis=1)  # remove column

      연도  날씨   high
도시
서울  2017  18   True
부산  2017  20   True
대전  2018  19  False
대구  2018  21   True
광주  2018  20  False

In [ ]:
data.drop(columns='car')  # the same as the above

      연도  날씨   high
도시
서울  2017  18   True
부산  2017  20   True
대전  2018  19  False
대구  2018  21   True
광주  2018  20  False

In [ ]:
data.drop(['car', 'high'], axis=1)

      연도  날씨
도시
서울  2017  18
부산  2017  20
대전  2018  19
대구  2018  21
광주  2018  20

## More on slicing and indexing
- Index Slicing:
  - Use 'loc' for label-based slicing.
  - Use 'iloc' for position-based slicing.
- Column Slicing:
  - Use 'loc' with : to slice columns by label.
  - Use a list of column names to select specific columns.

In [ ]:
# index slicing

data = {
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
}
df = pd.DataFrame(data)

# Index slicing using loc (label-based)
print(df.loc[1:3])

# Index slicing using iloc (integer position-based)
print(df.iloc[1:3])

   A   B    C
1  2  20  200
2  3  30  300
3  4  40  400
   A   B    C
1  2  20  200
2  3  30  300

In [ ]:
# column slicing

# Column slicing using loc (label-based)
print(df.loc[:, 'A':'B'])

# Column slicing using a list of column names
print(df[['A', 'B']])

   A   B
0  1  10
1  2  20
2  3  30
3  4  40
4  5  50
   A   B
0  1  10
1  2  20
2  3  30
3  4  40
4  5  50

## max, min, sum, mean, idxmax, idxmin

In [ ]:
df = pd.DataFrame(np.arange(12).reshape(4, 3),
                  columns=['A', 'B', 'C'],
                  index=['a', 'b', 'c', 'd'])
df

   A   B   C
a  0   1   2
b  3   4   5
c  6   7   8
d  9  10  11

In [ ]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
arr.argmax(), arr.argmax(axis=0)

(11, array([2, 2, 2, 2]))

In [ ]:
df.idxmax(axis=1)

a    C
b    C
c    C
d    C
dtype: object

In [ ]:
df.max(0), df.max() , type(df.max())  # defaults axis = 0

(A     9
 B    10
 C    11
 dtype: int64,
 A     9
 B    10
 C    11
 dtype: int64,
 pandas.core.series.Series)

In [ ]:
df.max(1), type(df.max(1))

(a     2
 b     5
 c     8
 d    11
 dtype: int64,
 pandas.core.series.Series)

In [ ]:
df.idxmax(0), df.idxmax(1)

(A    d
 B    d
 C    d
 dtype: object,
 a    C
 b    C
 c    C
 d    C
 dtype: object)

In [ ]:
df.max(0), df.min(0), df.sum(0), df.mean(0)

(A     9
 B    10
 C    11
 dtype: int64,
 A    0
 B    1
 C    2
 dtype: int64,
 A    18
 B    22
 C    26
 dtype: int64,
 A    4.5
 B    5.5
 C    6.5
 dtype: float64)

In [ ]:
df.A  # = df['A']

a    0
b    3
c    6
d    9
Name: A, dtype: int64

In [ ]:
df.A.max(), df.A.min()

(9, 0)

In [ ]:
df.max(0) - df.min(0)

A    9
B    9
C    9
dtype: int64

In [ ]:
f = lambda x: x.max() - x.min()

In [ ]:
df.apply(f)        # Apply a function along an axis of the DataFrame

A    9
B    9
C    9
dtype: int64

In [ ]:
df.apply(f, 1)   # array 처럼 행 1, 열 0

a    2
b    2
c    2
d    2
dtype: int64

In [ ]:
df.apply(lambda x: x.max() - x.min())

A    9
B    9
C    9
dtype: int64

In [ ]:
df.apply((lambda x: x.max() - x.min()), axis=1)

a    2
b    2
c    2
d    2
dtype: int64

In [ ]:
df

   A   B   C
a  0   1   2
b  3   4   5
c  6   7   8
d  9  10  11

In [ ]:
df.A.value_counts() ####

A
0    1
3    1
6    1
9    1
Name: count, dtype: int64

In [ ]:
df.apply(pd.value_counts)

<ipython-input-42-bd5faac84bc1>:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  df.apply(pd.value_counts)

      A    B    C
0   1.0  NaN  NaN
1   NaN  1.0  NaN
2   NaN  NaN  1.0
3   1.0  NaN  NaN
4   NaN  1.0  NaN
5   NaN  NaN  1.0
6   1.0  NaN  NaN
7   NaN  1.0  NaN
8   NaN  NaN  1.0
9   1.0  NaN  NaN
10  NaN  1.0  NaN
11  NaN  NaN  1.0

## Series

In [ ]:
# 파이썬 기본 타입인  딕셔너리로부터 시리즈를 만들 수 있다
dic = {'서울':800, '부산':150, '대구': 100}
dic

{'서울': 800, '부산': 150, '대구': 100}

In [ ]:
s = pd.Series(dic) ; s

서울    800
부산    150
대구    100
dtype: int64

In [ ]:
s.values, s.index, s.items

(array([800, 150, 100]),
 Index(['서울', '부산', '대구'], dtype='object'),
 <bound method Series.items of 서울    800
 부산    150
 대구    100
 dtype: int64>)

In [ ]:
s.value_counts()

800    1
150    1
100    1
Name: count, dtype: int64

In [ ]:
df.A.value_counts()

A
0    1
3    1
6    1
9    1
Name: count, dtype: int64

# Pandas - data processing

## sorting

In [ ]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [ ]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [ ]:
obj.sort_values(ascending=False)  # descending order

c    3
b    2
a    1
d    0
dtype: int64

In [ ]:
obj   # 위에서 sort를 해줬으나 obj의 결과는 변하지 않는다.

d    0
a    1
b    2
c    3
dtype: int64

In [ ]:
df = pd.DataFrame(np.arange(8).reshape((2, 4)), index=['three', 'one'],
                  columns=['d', 'a', 'b', 'c'])
df

       d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [ ]:
df.sort_index()     # alphabet 순 정렬

       d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [ ]:
df.sort_index(axis=1)    # 열(columns)을 기준으로 정렬

       a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [ ]:
try:
    df.sort_column()
except:
    print("Error: 'DataFrame' object has no attribute 'sort_column'")

Error: 'DataFrame' object has no attribute 'sort_column'

In [ ]:
df.sort_index(axis=1, ascending=False)   # descending order

       d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [ ]:
df = pd.DataFrame({'b': [4,7,3,2], 'a': [4,9,2,5], 'c': [5,3,7,9]})
df

   b  a  c
0  4  4  5
1  7  9  3
2  3  2  7
3  2  5  9

In [ ]:
df.sort_values(by='b')

   b  a  c
3  2  5  9
2  3  2  7
0  4  4  5
1  7  9  3

## ranking, idxmax, idxmin

In [ ]:
# 순위 매기기 rank
obj = pd.Series([100, 23, 99, 33])
obj.rank(ascending=False)

0    1.0
1    4.0
2    2.0
3    3.0
dtype: float64

In [ ]:
obj = pd.Series([100, 33, 99, 33])  # 동점이 있으면 평균값을 준다
obj.rank(ascending=False)

0    1.0
1    3.5
2    2.0
3    3.5
dtype: float64

In [ ]:
obj.rank(method='first', ascending=False)
# 동일한 값이 존재 할 경우 먼저 나타나는 것에게 높은 순위를 줄 수 있다

0    1.0
1    3.0
2    2.0
3    4.0
dtype: float64

In [ ]:
df = pd.DataFrame({'b': [4,7,3,2], 'a': [4,9,2,5], 'c': [5,3,7,9]})
df

   b  a  c
0  4  4  5
1  7  9  3
2  3  2  7
3  2  5  9

In [ ]:
df.rank()

     b    a    c
0  3.0  2.0  2.0
1  4.0  4.0  1.0
2  2.0  1.0  3.0
3  1.0  3.0  4.0

In [ ]:
df.rank(axis=1, ascending=False)      #행 기준으로 rank를 수행

     b    a    c
0  2.5  2.5  1.0
1  2.0  1.0  3.0
2  2.0  3.0  1.0
3  3.0  2.0  1.0

In [ ]:
# NaN이 있는 경우 빼고 계산한다
df = pd.DataFrame({'b': [4, 7, 3, 2], 'a': [4,9,2,5], 'c': [5,3,7,np.nan]})
df

   b  a    c
0  4  4  5.0
1  7  9  3.0
2  3  2  7.0
3  2  5  NaN

In [ ]:
df.sum(0)

b    16.0
a    20.0
c    15.0
dtype: float64

In [ ]:
print(df.sum(0))
print(df.mean(0))

b    16.0
a    20.0
c    15.0
dtype: float64
b    4.0
a    5.0
c    5.0
dtype: float64

In [ ]:
df.sum(skipna=False)
# NaN이 있으면 이를 반영하여 스킵하지 않는다
# skipna 은 skip NaN을 뜻함.

b    16.0
a    20.0
c     NaN
dtype: float64

In [ ]:
# 최대치, 최소치가 있는 위치를 반환한다
print(df.idxmax(), df.idxmin())

b    1
a    1
c    2
dtype: int64 b    3
a    2
c    1
dtype: int64

## unique, value_counts, isin

In [ ]:
# 유니크한 값 찾기 (set)
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [ ]:
set(obj)

{'a', 'b', 'c', 'd'}

In [ ]:
obj.unique()   ## value 값의 종류를 확인 할 수 있다.

array(['c', 'a', 'd', 'b'], dtype=object)

In [ ]:
# 빈도수를 간단히 알 수 있다. 빈도수가 높은 순으로 정렬된다.
obj.value_counts()

c    3
a    3
b    2
d    1
Name: count, dtype: int64

In [ ]:
# 빈도수와 관련없이 나타나는 순서대로 보려면
obj.value_counts(sort=False)

c    3
a    3
d    1
b    2
Name: count, dtype: int64

In [ ]:
# 특정한 내용이 들어있는지 알려면 isin()을 사용한다
mask = obj.isin(['b', 'c']); mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [ ]:
obj[mask] ## obj에서 mask 값이 true인 값만을 출력

0    c
5    b
6    b
7    c
8    c
dtype: object

In [ ]:
# 아래는 같은 결과를 얻는다
obj[obj.isin(['b', 'c'])]

0    c
5    b
6    b
7    c
8    c
dtype: object

## apply, fillna

In [ ]:
df = pd.DataFrame({'X':['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'],
                   'Y':['f', 'g', 'd', 'g', 'h', 'e', 'd', 'h', 'f'],
                   'Z':['a', 'e', 'd', 'g', 'd', 'e', 'q', 'b', 'c']})
df

   X  Y  Z
0  c  f  a
1  a  g  e
2  d  d  d
3  a  g  g
4  a  h  d
5  b  e  e
6  b  d  q
7  c  h  b
8  c  f  c

In [ ]:
df.apply(lambda s: s.value_counts())    # same as the below

     X    Y    Z
a  3.0  NaN  1.0
b  2.0  NaN  1.0
c  3.0  NaN  1.0
d  1.0  2.0  2.0
e  NaN  1.0  2.0
f  NaN  2.0  NaN
g  NaN  2.0  1.0
h  NaN  2.0  NaN
q  NaN  NaN  1.0

In [ ]:
# 각 항목이 들어 있는 갯수를 센다. 없는 값은 NaN으로 표시된다
df.apply(pd.value_counts)

<ipython-input-79-87300dc3e768>:2: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  df.apply(pd.value_counts)
<ipython-input-79-87300dc3e768>:2: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  df.apply(pd.value_counts)
<ipython-input-79-87300dc3e768>:2: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  df.apply(pd.value_counts)

     X    Y    Z
a  3.0  NaN  1.0
b  2.0  NaN  1.0
c  3.0  NaN  1.0
d  1.0  2.0  2.0
e  NaN  1.0  2.0
f  NaN  2.0  NaN
g  NaN  2.0  1.0
h  NaN  2.0  NaN
q  NaN  NaN  1.0

In [ ]:
df.apply(pd.value_counts).fillna(0) ## fillna 은 fill NaN을 뜻한다.

<ipython-input-80-e5df94fc31f0>:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  df.apply(pd.value_counts).fillna(0) ## fillna 은 fill NaN을 뜻한다.
<ipython-input-80-e5df94fc31f0>:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  df.apply(pd.value_counts).fillna(0) ## fillna 은 fill NaN을 뜻한다.
<ipython-input-80-e5df94fc31f0>:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  df.apply(pd.value_counts).fillna(0) ## fillna 은 fill NaN을 뜻한다.

     X    Y    Z
a  3.0  0.0  1.0
b  2.0  0.0  1.0
c  3.0  0.0  1.0
d  1.0  2.0  2.0
e  0.0  1.0  2.0
f  0.0  2.0  0.0
g  0.0  2.0  1.0
h  0.0  2.0  0.0
q  0.0  0.0  1.0

## dropna (missing value)

In [ ]:
# 결측치 처리
from numpy import nan as NA
data = pd.Series([1, NA, 3.5, NA, 7]); data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [ ]:
data.dropna() # data에서 Na값들을 지움

0    1.0
2    3.5
4    7.0
dtype: float64

In [ ]:
# 같은 결과
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [ ]:
df = pd.DataFrame([[NA, 6.5, 3.], [NA, NA, NA],
                  [NA, NA, NA], [NA, 6.5, 3.]])
df

    0    1    2
0 NaN  6.5  3.0
1 NaN  NaN  NaN
2 NaN  NaN  NaN
3 NaN  6.5  3.0

In [ ]:
df.dropna()   # 한 항목이라도 NA가 있으면 해당 행을 삭제한다

Empty DataFrame
Columns: [0, 1, 2]
Index: []

In [ ]:
df.dropna(how='all') # 행의 모든 항목이 NA일때 해당 행을 삭제한다

    0    1    2
0 NaN  6.5  3.0
3 NaN  6.5  3.0

In [ ]:
df.dropna(axis=1)  # 컬럼에 대한 삭제

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [ ]:
df.dropna(axis=1, how='all')

     1    2
0  6.5  3.0
1  NaN  NaN
2  NaN  NaN
3  6.5  3.0

In [ ]:
df = pd.DataFrame(np.random.randn(7 , 3))
df.iloc[:4, 1] = NA
df.iloc[:2, 2] = NA
df.iloc[0,0] = NA
df

          0         1         2
0       NaN       NaN       NaN
1 -0.234812       NaN       NaN
2  0.073286       NaN -0.423433
3  0.526583       NaN  0.856378
4  0.169831  0.726369 -0.119155
5 -0.287323 -0.849630  0.212585
6 -0.694264  0.240518  1.028217

In [ ]:
df.dropna(thresh=2) # Keep only the rows with at least 2 non-NA values.

          0         1         2
2  0.073286       NaN -0.423433
3  0.526583       NaN  0.856378
4  0.169831  0.726369 -0.119155
5 -0.287323 -0.849630  0.212585
6 -0.694264  0.240518  1.028217

In [ ]:
# 컬럼별로 다른 값을 채울 수 있다. 사전을 사용한다
df.fillna({1: 0.5, 2: -1})

          0         1         2
0       NaN  0.500000 -1.000000
1 -0.234812  0.500000 -1.000000
2  0.073286  0.500000 -0.423433
3  0.526583  0.500000  0.856378
4  0.169831  0.726369 -0.119155
5 -0.287323 -0.849630  0.212585
6 -0.694264  0.240518  1.028217

## concat
- concat 명령을 사용하면 기준 열(key column)을 사용하지 않고 단순히 데이터를 연결(concatenate)한다.
- 기본적으로는 위/아래로 데이터 행을 연결한다. 단순히 두 시리즈나 데이터프레임을 연결하기 때문에 인덱스 값이 중복될 수 있다.

In [ ]:
df1 = pd.DataFrame(np.arange(12).reshape(3,4)) ; df1

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [ ]:
df2 = pd.DataFrame(np.ones((3,4)),
                   index=['a','b','c']) ; df2

     0    1    2    3
a  1.0  1.0  1.0  1.0
b  1.0  1.0  1.0  1.0
c  1.0  1.0  1.0  1.0

In [ ]:
pd.concat([df1,df2])

     0    1     2     3
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0
a  1.0  1.0   1.0   1.0
b  1.0  1.0   1.0   1.0
c  1.0  1.0   1.0   1.0

In [ ]:
pd.concat([df1,df2], axis=1)

     0    1     2     3    0    1    2    3
0  0.0  1.0   2.0   3.0  NaN  NaN  NaN  NaN
1  4.0  5.0   6.0   7.0  NaN  NaN  NaN  NaN
2  8.0  9.0  10.0  11.0  NaN  NaN  NaN  NaN
a  NaN  NaN   NaN   NaN  1.0  1.0  1.0  1.0
b  NaN  NaN   NaN   NaN  1.0  1.0  1.0  1.0
c  NaN  NaN   NaN   NaN  1.0  1.0  1.0  1.0

## merge
- column 을 기준으로 결합할 때
- merge() and join()
  - merge():
    - 공통의 열(column)을 기준으로 데이터를 결합 (SQL 의 JOIN 과 유사)
    - 더 많은 유연성을 제공하기 때문에, top-level 함수로 구현
  - join():
    - 인덱스(index)를 기준으로 두 DataFrame을 결합
    - DataFrame 객체에 특화된 메서드이기 때문이기 때문에 df1.join(df2) 와 같은 방식으로 사용 (pd.join() 없음)

In [ ]:
df1 = pd.DataFrame({'key': ['a', 'b', 'c'], 'A': [1, 2, 3]})
df2 = pd.DataFrame({'key': ['a', 'b', 'd'], 'B': [4, 5, 6]})
df1

  key  A
0   a  1
1   b  2
2   c  3

In [ ]:
df2

  key  B
0   a  4
1   b  5
2   d  6

In [ ]:
pd.merge(df1, df2, on='key')

  key  A  B
0   a  1  4
1   b  2  5

In [ ]:
pd.merge(df1, df2, on='key', how='outer')

  key    A    B
0   a  1.0  4.0
1   b  2.0  5.0
2   c  3.0  NaN
3   d  NaN  6.0

## join
- Index 를 기준으로 결합

In [ ]:
import pandas as pd

df1 = pd.DataFrame({'A': [1, 2, 3]}, index=['a', 'b', 'c'])
df2 = pd.DataFrame({'B': [4, 5, 6]}, index=['a', 'b', 'd'])
df1

   A
a  1
b  2
c  3

In [ ]:
df2

   B
a  4
b  5
d  6

In [ ]:
# 인덱스를 기준으로 결합
df1.join(df2)

   A    B
a  1  4.0
b  2  5.0
c  3  NaN

In [ ]:
df1.join(df2, how='outer')

     A    B
a  1.0  4.0
b  2.0  5.0
c  3.0  NaN
d  NaN  6.0

## groupby (**) and crosstab
- groupby():
  - 데이터를 특정 열을 기준으로 그룹화한 후, 다양한 집계 연산을 적용. (데이터의 요약과 집계에 매우 유용)
  - 추가 메서드 없이 실행하면 DataFrameGroupBy 오브젝트가 생성
  - 여기에 추가 연산 메서드를 입력하면, 해당 열의 그룹화된 데이터에 대해서 연산이 수행
- crosstab():
  - 두 개 이상의 범주형 변수 간의 빈도나 교차 테이블을 생성. (범주형 데이터를 분석할 때 유용하며, 다양한 집계 함수도 적용)

In [ ]:
data = {'Team': ['Riders', 'Riders', 'Devils', 'Devils', 'Kings',
                 'Kings', 'Kings', 'Kings', 'Riders', 'Royals', 'Royals', 'Riders'],
        'Rank': [1, 2, 2, 3, 3,4 ,1 ,1,2 , 4,1,2],
        'Year': [2014,2015,2014,2015,2014,2015,2016,2017,2016,2014,2015,2017],
        'Points':[876,789,863,673,741,812,756,788,694,701,804,690]}

df = pd.DataFrame(data); df

      Team  Rank  Year  Points
0   Riders     1  2014     876
1   Riders     2  2015     789
2   Devils     2  2014     863
3   Devils     3  2015     673
4    Kings     3  2014     741
5    Kings     4  2015     812
6    Kings     1  2016     756
7    Kings     1  2017     788
8   Riders     2  2016     694
9   Royals     4  2014     701
10  Royals     1  2015     804
11  Riders     2  2017     690

In [ ]:
df.groupby('Team').groups    # view groups (shows indices)

{'Devils': [2, 3], 'Kings': [4, 5, 6, 7], 'Riders': [0, 1, 8, 11], 'Royals': [9, 10]}

In [ ]:
df.groupby('Year').groups

{2014: [0, 2, 4, 9], 2015: [1, 3, 5, 10], 2016: [6, 8], 2017: [7, 11]}

In [ ]:
df.groupby(['Team','Year']).groups

{('Devils', 2014): [2], ('Devils', 2015): [3], ('Kings', 2014): [4], ('Kings', 2015): [5], ('Kings', 2016): [6], ('Kings', 2017): [7], ('Riders', 2014): [0], ('Riders', 2015): [1], ('Riders', 2016): [8], ('Riders', 2017): [11], ('Royals', 2014): [9], ('Royals', 2015): [10]}

In [ ]:
grouped = df.groupby('Year')

for name, group in grouped:
   print (name)
   print (group)

2014
     Team  Rank  Year  Points
0  Riders     1  2014     876
2  Devils     2  2014     863
4   Kings     3  2014     741
9  Royals     4  2014     701
2015
      Team  Rank  Year  Points
1   Riders     2  2015     789
3   Devils     3  2015     673
5    Kings     4  2015     812
10  Royals     1  2015     804
2016
     Team  Rank  Year  Points
6   Kings     1  2016     756
8  Riders     2  2016     694
2017
      Team  Rank  Year  Points
7    Kings     1  2017     788
11  Riders     2  2017     690

- crosstab()

In [ ]:
pd.crosstab(df['Team'],df['Year'])

Year    2014  2015  2016  2017
Team
Devils     1     1     0     0
Kings      1     1     1     1
Riders     1     1     1     1
Royals     1     1     0     0

- more on groupby()

In [ ]:
# selecting group
grouped = df.groupby('Year')
grouped.get_group(2014)

     Team  Rank  Year  Points
0  Riders     1  2014     876
2  Devils     2  2014     863
4   Kings     3  2014     741
9  Royals     4  2014     701

In [ ]:
# aggregations
grouped = df.groupby('Year')
grouped['Points'].agg(np.mean)

<ipython-input-30-18c298456022>:3: FutureWarning: The provided callable <function mean at 0x7b268a0ec310> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  grouped['Points'].agg(np.mean)

Year
2014    795.25
2015    769.50
2016    725.00
2017    739.00
Name: Points, dtype: float64

In [ ]:
# transformation
grouped = df.groupby('Team')
score = lambda x: (x - x.mean()) / x.std()
grouped.transform(score)

        Rank      Year    Points
0  -1.500000 -1.161895  1.284327
1   0.500000 -0.387298  0.302029
2  -0.707107 -0.707107  0.707107
3   0.707107  0.707107 -0.707107
4   0.500000 -1.161895 -1.042333
5   1.166667 -0.387298  1.183401
6  -0.833333  0.387298 -0.572108
7  -0.833333  1.161895  0.431040
8   0.500000  0.387298 -0.770596
9   0.707107 -0.707107 -0.707107
10 -0.707107  0.707107  0.707107
11  0.500000  1.161895 -0.815759

In [ ]:
# filtration
df.groupby('Team').filter(lambda x: len(x) >= 3)

      Team  Rank  Year  Points
0   Riders     1  2014     876
1   Riders     2  2015     789
4    Kings     3  2014     741
5    Kings     4  2015     812
6    Kings     1  2016     756
7    Kings     1  2017     788
8   Riders     2  2016     694
11  Riders     2  2017     690

# Exercise

In [ ]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [10,11,12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
df = pd.DataFrame(a,
                  columns=['A','B','C'],
                  index=['a','b','c','d'])
df

    A   B   C
a   1   2   3
b   4   5   6
c   7   8   9
d  10  11  12

In [ ]:
df['A':'C']        # not working !

Empty DataFrame
Columns: [A, B, C]
Index: []

In [ ]:
df[['A','C']]

    A   C
a   1   3
b   4   6
c   7   9
d  10  12

In [ ]:
df.iloc[:, :2]

    A   B
a   1   2
b   4   5
c   7   8
d  10  11

In [ ]:
df.iloc[:, [0,2]]

    A   C
a   1   3
b   4   6
c   7   9
d  10  12

In [ ]:
df.iloc[:, :-1]

    A   B
a   1   2
b   4   5
c   7   8
d  10  11

In [ ]:
df.loc['a':'c'][['A','C']]

   A  C
a  1  3
b  4  6
c  7  9

In [ ]:
(df.loc['a':'c']).iloc[:,0:2]

   A  B
a  1  2
b  4  5
c  7  8

In [ ]:
df.A.loc['b'], df.A['b']

(4, 4)

In [ ]:
# end