<a href="https://colab.research.google.com/github/rtajeong/M1_2025/blob/main/gg07_file_csv_rev1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 파일 생성

In [ ]:
from pandas import DataFrame, Series
import pandas as pd

f = open("test.csv", "w")
f.write("1,2,3,4,5 \n")
f.close()

In [ ]:
!cat test.csv
#!type test.csv

1,2,3,4,5

In [ ]:
with open("test.csv", "a") as f:
    f.write("1,2,3,4,5 \n")
    f.write("1,2,3,4,5 \n")

In [ ]:
!cat test.csv
#!type test.csv

1,2,3,4,5
1,2,3,4,5
1,2,3,4,5

In [ ]:
with open("test.csv",'r') as f:
    for line in f:
        print(line, end='\t')

1,2,3,4,5
	1,2,3,4,5
	1,2,3,4,5

## 옵션
'r'	Open a file for reading. (default)  
'w'	Open a file for writing. Creates a new file if it does not exist or truncates the file if it exists.  
'x'	Open a file for exclusive creation. If the file already exists, the operation fails.  
'a'	Open for appending at the end of the file without truncating it.   Creates a new file if it does not exist.
't'	Open in text mode. (default)  
'b'	Open in binary mode.  
'+'	Open a file for updating (reading and writing)

In [ ]:
with open("test.csv", "w") as f:
    f.write("a,b,c,d,message \n")
    f.write("1,2,3,4,hello \n")
    f.write("5,6,7,8,world \n")
    f.write("9,10,11,12,foo \n")

In [ ]:
!cat test.csv
# !type test.csv

a,b,c,d,message
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [ ]:
pd.read_csv('test.csv')  # 자동으로 컬럼명을 만든다

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [ ]:
pd.read_csv('test.csv', header=None)

   0   1   2   3         4
0  a   b   c   d  message
1  1   2   3   4    hello
2  5   6   7   8    world
3  9  10  11  12      foo

In [ ]:
pd.read_csv('test.csv', header=1)

   1   2   3   4  hello
0  5   6   7   8  world
1  9  10  11  12    foo

In [ ]:
pd.read_csv('test.csv', names=['A','B','C','D','E'])

   A   B   C   D         E
0  a   b   c   d  message
1  1   2   3   4    hello
2  5   6   7   8    world
3  9  10  11  12      foo

In [ ]:
!cat test.csv

a,b,c,d,message
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [ ]:
pd.read_csv('test.csv', nrows=2)  # 상위 2개의 행만 읽음
# pd.read_csv('data/ex1.csv', index_col='message')

   a  b  c  d message
0  1  2  3  4   hello
1  5  6  7  8   world

In [ ]:
df = pd.read_csv('test.csv', index_col='a')
df

    b   c   d message
a
1   2   3   4   hello
5   6   7   8   world
9  10  11  12     foo

In [ ]:
df.to_csv('output.csv')

In [ ]:
!cat output.csv

a,b,c,d,message
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

## 디렉토리 관리

In [ ]:
!pwd

/content

In [ ]:
import os
os.getcwd()   # pwd

'/content'

In [ ]:
os.listdir()  # ls

['.config', 'test.csv', 'sample_data']

In [ ]:
if 'data' not in os.listdir():
    os.mkdir('data')

In [ ]:
os.listdir()

['.config', 'output.csv', 'data', 'test.csv', 'sample_data']

In [ ]:
os.chdir("data")
os.listdir()

[]

In [ ]:
os.chdir("..")

In [ ]:
# os.rename('data','new_one')
os.remove('output.csv')
# os.rmdir('new_one')

In [ ]:
os.listdir()

['.config', 'data', 'test.csv', 'sample_data']

## JSON
- 속성(attribute)-값(value) 쌍으로 이루어진 개방형 표준 포맷 (앱 프로그램에서 자주 사용)
- json 에서는 """. . . """ 로 묶어 표현해야 함.

In [ ]:
import json

In [ ]:
# json은 python에서처럼 '으로 하면 안된다. 현재 """로 감싸 문자열로 저장되어 있기 때문에
# javascript에서는 '를 string 값으로 인식하지 않아서 에러 발생
obj = """
{
    "name": "Kim",
    "places_lived": ["Seoul", "Korea"],
    "pet": null,
    "siblings": [{"name": "Scott", "age":25, "pet":"Zuko"}]
}
"""

In [ ]:
print(type(obj))
print(obj)

<class 'str'>

{
    "name": "Kim",
    "places_lived": ["Seoul", "Korea"],
    "pet": null,
    "siblings": [{"name": "Scott", "age":25, "pet":"Zuko"}]
}

In [ ]:
result = json.loads(obj)   # JSON decoding (json(string) -> dict)
result

{'name': 'Kim',
 'places_lived': ['Seoul', 'Korea'],
 'pet': None,
 'siblings': [{'name': 'Scott', 'age': 25, 'pet': 'Zuko'}]}

In [ ]:
type(result)

dict

In [ ]:
asjson = json.dumps(result)    # JSON encoding (dict -> json (string))
asjson

'{"name": "Kim", "places_lived": ["Seoul", "Korea"], "pet": null, "siblings": [{"name": "Scott", "age": 25, "pet": "Zuko"}]}'

In [ ]:
type(asjson)

str